const rules = {
    'git': ['git', 'merge', 'github', 'gitlab'],
    'docker': ['docker', 'container'],
    'javascript': ['javscript', 'nodejs', 'node.js', 'webpack', '.js', 'ckeditor', 'typeorm', 'ts', 'typescript', 'mocha', 'ionic', 'json', 'yeoman', 'gruntjs', 'gulp', 'es7', 'es8', 'javascript', 'js', 'webpack', 'frontend', 'web-developer', 'frontend', 'callback', 'jquery', 'html/css', 'lodash', 'underscore', 'eslint', 'web'],
    'security': ['vulneribility', 'firewall', 'security', 'sercurity', 'cqrs', 'csrf', 'malware', 'bao-mat'],
    'database': ['redis', 'sql', 'postgres', 'mysql', 'sqlserver', 'neo4j'],
    'algorithm': ['algorithm'],
    'social-networking': ['social-networking', 'messenger', 'facebook', 'instagram', 'tiktok', 'discord', 'youtube'],
    'golang': ['golang'],
    'react-js': ['react', 'hook', 'create-react-app'],
    'css': ['css'],
    'web-server': ['web-server', 'nginx', 'apache', 'tomcat', 'iis'],
    'ai': ['yolo', 'deeplearning', 'machine-learning', 'prediction', 'classification', 'scikit-learn', 'recognition', 'neural'],
    'iot': ['iot'],
    'ide': ['ide', 'editor', 'vim', 'visual-studio'],
    'os': ['hackintosh', 'linux', 'windows', 'ubuntu', 'centos', 'terminal'],
    'mobile': ['flutter', 'xamarin', 'android', 'ios', 'swift', 'iphone', 'phone', 'kotlin'],
    'regex': ['regex', 'regular-expression', 'bieu-thuc-chinh-quy'],
    'agile': ['agile', 'scrum'],
    'ruby': ['ruby', 'rail', 'gem'],
    'devops': ['devops', 'solution-architecture', 'jenkins', 'vlan', 'kubernetes', 'network'],
    'blockchain': ['blockchain'],
    'php': ['blade', 'magento', 'php', 'symfony', 'laravel', 'wordpress', 'xampp', 'zend'],
    'cloud-computing': ['aws', 'cloud', 's3', 'amazon'],
    'testing': ['test', 'kiem-thu'],
    'react-native': ['react-native'],
    'design': ['ui', 'svg'],
    'c++': ['c++', 'cpp', 'gcc'],
    'java': ['spring', 'swing', 'thymeleaf', 'jdbc'],
    'micro-services': ['rabbitmq', 'message-broker', 'microservice'],
    'python': ['python', 'pandas', 'data-preprocessing', 'numpy', 'keras', 'tensorflow', 'django'],
    'angular-js': ['angular'],
    'vue-js': ['vue', 'vue-js'],
    'dot-net': ['.net', 'c#', 'vba'],
    'game-programming': ['unity'],
    'oop': ['oop', 'pattern', 'designpatterns'],
    'api': ['api'],
    'blockchain': ['blockchain', 'ethereum'],
    'browser': ['browser', 'chrome', 'firefox', 'chromium'],
    'seo': ['marketing', 'seo']
};

module.exports = rules;